Pass.muxi tech.xyz auth fix
Muxi-X/muxi_auth_fe pull request #25
Opened 2021-06-10 05:02 UTC by qingxiangying

2021-07-02 12:20 UTC, zxc0328 requested changes

2021-07-02 12:20 UTC, zxc0328 commented on src/common/cookie.js
> +  // let name = cname;
多余的代码删掉

2021-07-02 12:20 UTC, zxc0328 commented on src/common/service.js
> +    // 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
header 不用的话直接删掉就行

2021-07-02 12:20 UTC, zxc0328 commented on src/common/service.js
> +      '/auth/api/oauth?response_type=code&client_id=51f03389-2a18-4941-ba73-c85d08201d42',
client_id 是通过参数在 URL 里面传给你的，不是写死的。

2021-07-02 12:20 UTC, zxc0328 commented on src/common/service.js
> +    let client_secret = '7d52480f-730d-45a1-99cc-1397985ebe0e';
同上，别写死了

2021-07-02 12:20 UTC, zxc0328 commented on src/common/service.js
> +    let client_secret = '7d52480f-730d-45a1-99cc-1397985ebe0e';
别写死了

2021-07-02 12:20 UTC, zxc0328 commented on src/pages/login/login.js
> +  //         if (landing) {
没用的代码就删掉，别注释。有用就留着。总之注释掉的代码是不好的，后面维护的人也不知道你这个代码要不要用了

2021-07-02 12:20 UTC, zxc0328 commented on src/pages/login/login.js
> +          let landing = 'pass.muxi-tech.xyz/';
landing 要从 cookie 获取。

2021-07-02 12:20 UTC, zxc0328 commented on src/pages/login/login.js
> +
注释问题，同上。

2021-07-06 03:18 UTC, zxc0328 requested changes

2021-07-06 03:18 UTC, zxc0328 commented on src/common/getFromUrl.js
> +export default getQueryVariable;
如果复制网上的代码，也要改一下代码风格和我们自己的代码保持一致。比如用 const 和 let。var 现在基本不用了。

然后解析 query string 这个可以用这个库 https://www.npmjs.com/package/query-string。比较保险一点。你也可以去 github 上看一下这个库的源码实现。

2021-07-06 03:18 UTC, zxc0328 commented on src/common/service.js
> +    let client_id = getFromUrl('client_id');
统一在组件里解析好，调接口的时候传。不然你反复解析，做了很多无用功。

2021-07-06 03:18 UTC, zxc0328 commented on src/pages/register/register.js
> +// import Background from '../../images/login.png';
不用的直接删掉

2021-07-06 03:20 UTC, qingxiangying commented on src/common/getFromUrl.js
> +export default getQueryVariable;
好的

2021-07-06 12:28 UTC, zxc0328 approved these changes

2021-07-06 12:28 UTC, merged